export default [
  {
    key:"Klasik",
    label:"Klasik",
    url:"/images/music/classic.jpg",
  },
  {
    key:"Jazz",
    label:"Jazz",
    url:"/images/music/jazz.jpg",
  },
  {
    key:"Country",
    label:"Country",
    url:"/images/music/country.jpg",
  },
  {
    key:"Rock",
    label:"Rock",
    url:"/images/music/rock.jpg",
  },
  {
    key:"Blues",
    label:"Blues",
    url:"/images/music/blues.jpg",
  },
  {
    key:"Pop",
    label:"Pop",
    url:"/images/music/pop.jpg",
  },
  {
    key:"Techno",
    label:"Techno",
    url:"/images/music/techno.jpg",
  },
  {
    key:"Balada",
    label:"Balada",
    url:"/images/music/balada.jpg",
  },
  {
    key:"Reggae",
    label:"Reggae",
    url:"/images/music/reggea.jpg",
  },
  {
    key:"RnB",
    label:"RnB",
    url:"/images/music/classig.jpg",
  },
  {
    key:"Dangdut",
    label:"Dangdut",
    url:"/images/music/dangdut.jpg",
  },
  {
    key:"Death Metal",
    label:"Death Metal",
    url:"/images/music/rap.jpg",
  },
  {
    key:"Rap",
    label:"Rap",
    url:"/images/music/rap.jpg",
  },
  {
    key:"Hip Hop",
    label:"Hip Hop",
    url:"/images/music/hiphop.jpg",
  },
  {
    key:"Funk",
    label:"Funk",
    url:"/images/music/classic.jpg",
  },
  {
    key:"Electronic",
    label:"Electronic",
    url:"/images/music/electronic.jpg",
  },
  {
    key:"Latin",
    label:"Latin",
    url:"/images/music/metal.jpg",
  },
  {
    key:"Metal",
    label:"Metal",
    url:"/images/music/metal.jpg",
  },
]
