export default [
  {
    value:"klasik",
    label:"klasik",
    url:"/images/music/classic.jpg",
  },
  {
    value:"jazz",
    label:"jazz",
    url:"/images/music/jazz.jpg",
  },
  {
    value:"country",
    label:"country",
    url:"/images/music/country.jpg",
  },
  {
    value:"rock",
    label:"rock",
    url:"/images/music/rock.jpg",
  },
  {
    value:"blues",
    label:"blues",
    url:"/images/music/blues.jpg",
  },
  {
    value:"pop",
    label:"pop",
    url:"/images/music/pop.jpg",
  },
  {
    value:"techno",
    label:"techno",
    url:"/images/music/techno.jpg",
  },
  {
    value:"balada",
    label:"balada",
    url:"/images/music/balada.jpg",
  },
  {
    value:"reggae",
    label:"reggae",
    url:"/images/music/reggea.jpg",
  },
  {
    value:"rnb",
    label:"RnB",
    url:"/images/music/classig.jpg",
  },
  {
    value:"dangdut",
    label:"dangdut",
    url:"/images/music/dangdut.jpg",
  },
  {
    value:"death metal",
    label:"death metal",
    url:"/images/music/rap.jpg",
  },
  {
    value:"rap",
    label:"rap",
    url:"/images/music/rap.jpg",
  },
  {
    value:"hip hop",
    label:"hip hop",
    url:"/images/music/hiphop.jpg",
  },
  {
    value:"funk",
    label:"funk",
    url:"/images/music/classic.jpg",
  },
  {
    value:"electronic",
    label:"electronic",
    url:"/images/music/electronic.jpg",
  },
  {
    value:"latin",
    label:"latin",
    url:"/images/music/metal.jpg",
  },
  {
    value:"metal",
    label:"metal",
    url:"/images/music/metal.jpg",
  },
]
